name: CI to Docker Hub

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        id: "Checkout"
        uses: actions/checkout@v2.5.0
      - name: "Docker login"
        id: "login"
        uses: docker/login-action@v2.1.0
        with:
          username: refferency
          password: Cbnb1337!
      - name: "Docker build & push"
        id: "build"
        uses: docker/build-push-action@v3.2.0
        with:
          dockerfile: ./Dockerfile
          push: true
          tags: refferency/lab5:latest
